roleId: MORGANA
displayName: Morgana
camp: EVIL
description: Appears as Merlin to Percival.
canJoinMission: true
canVote: true
canLead: true
canAssassinate: false
knowledgeRules:
  - type: MISLEAD_PERCIVAL
actionCapabilities: []
passiveTraits: []

